[tool.poetry]
name = "pycalc"
version = "0.1.0"
description = ""
authors = ["Zaid"]
readme = "README.md"
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pyinstaller = "^6.10.0"
pygame = "2.5.2"
[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
poethepoet = "^0.28.0"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks]
updateview = "pyside6-uic -o ./src/main/ui/gen/ui_calculadora_view.py ./assets/ui_calculadora_view.ui"
updatercc = "pyside6-rcc -o ./src/main/icons_rc.py ./assets/icons.qrc"
updateall = ["updateview", "updatercc"]
format = "ruff format"
check = "ruff check"
runtest = "pytest ./src/test"
runapp = "python ./src/main/main.py"
build = "pyinstaller --clean --noconsole --name=PyCalc6 ./src/main/main.py "
add_assets = "python utilassets.py"
build_all = ["build", "add_assets"]
run_and_update = ["updateall", "runapp"]

